### ISSUE TITLE
`DESCRIPTION` file metadata

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#1]
Need input on:

- [ ] Authors: Should I copy over the full list of authors from `covidHubUtils` (https://github.com/reichlab/covidHubUtils/blob/ebe1401353075c3c0518aa0f847757dfc3b8cbde/DESCRIPTION#L4-L48)
- [x] **License:** Sick with MIT?

**Comment by elray1** [comment]
We discussed in a call:
