### ISSUE TITLE
split this package into three packages for different intended audiences

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubUtils#120]
hubAdmin: all the stuff for setting up a hub
hubData (name not fully settled): access and work with data in a hub

**Comment by elray1** [comment]
As part of this, we could consider merging functionality from hubCI into hubAdmin

**Comment by annakrystalli** [comment]
Throwing the idea to use `hubConnect` instead of `hubData` for anything to do with connecting to hubs and accessing data.

That way if we do end up creating a package with hub data we can use `hubData` for that?

**Comment by elray1** [comment]
I don't have a strong opinion -- `hubConnect` is ok.

**Comment by annakrystalli** [comment]
I guess that in turn depends on what other functionality you might envisage for this package.

**Comment by elray1** [comment]
Yeah.  I don't have a specific answer to that question.  I think there's nothing specific in the works, but I remember that in some past conversation people abstractly threw out an idea that there might be other general utility functions for working with hub data.  Maybe stuff about converting between model output types?  Common pieces of functionality for standardizing/aligning/switching between representations of reference dates, target dates, and horizons?

**Comment by nickreich** [comment]
I think some arguments for `hubData` over `hubConnect` are that 

- it seems like the obvious home for some simple and small example data objects
- this package would seem to be a natural home for [functions requested here](https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/136), that are for summaries/operations on hub data

**Comment by annakrystalli** [comment]
Ok! `hubData` it is.

**Comment by annakrystalli** [comment]
Completed in:
- https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/pull/143
- https://github.com/Infectious-Disease-Modeling-Hubs/hubData/pull/1
- https://github.com/Infectious-Disease-Modeling-Hubs/hubAdmin/pull/1
