### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubUtils#126]
Use definition below 
[Definitions of roles](https://r-pkgs.org/description.html#sec-description-authors-at-r) (Author, maintainer, contributor, etc…)

Going forward, ensure that PRs from new contributors include an update to authorship roles (for R packages, in description file)

**Comment by elray1** [comment]
I think a contributor role would make sense for me.

**Comment by nickreich** [comment]
I think a ctb role makes sense for me. my ORCID: 0000-0003-3503-9899
