### ISSUE TITLE
add hard-coded global variables or datasets with common location codes

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#127]
E.g. it'd be nice to access the standard US location codes for defining say, locations in a `create_task_id()` call. These could be taken from `covidHubUtils::hub_locations$fips`

**Comment by annakrystalli** [comment]
Nice idea! Here's the full table of US location data:
``` r
covidHubUtils::hub_locations
#> # A tibble: 3,202 × 7
#>    fips  location_name        population geo_type geo_value abbreviation
#>    <chr> <chr>                     <dbl> <chr>    <chr>     <chr>       
#>  1 US    United States         332875137 state    us        US          
#>  2 01    Alabama                 4903185 state    al        AL          
#>  3 02    Alaska                   731545 state    ak        AK          
#>  4 04    Arizona                 7278717 state    az        AZ          
#>  5 05    Arkansas                3017804 state    ar        AR          
#>  6 06    California             39512223 state    ca        CA          
#>  7 08    Colorado                5758736 state    co        CO          
#>  8 09    Connecticut             3565287 state    ct        CT          
#>  9 10    Delaware                 973764 state    de        DE          
#> 10 11    District of Columbia     705749 state    dc        DC          
#> # ℹ 3,192 more rows
#> # ℹ 1 more variable: full_location_name <chr>
```

<sup>Created on 2024-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

- Should we keep the info as a `tibble` which includes additional metadata? (could be useful for plotting/merging into queried data)
- If so, how much of additional metadata should we include? E.g. should we include population info which may fluctuate?
- Any suggestions of an up to date source of EU location info?
- Any other location info that could be useful?

**Comment by nickreich** [comment]
My responses to questions above:

 - No strong feelings on `tibble` or not. I see that we already have `tibble` as a dependency, so maybe not a huge deal to keep it that way? But I also don't see a strong reason to keep it as a `tibble`.
 - I'd vote for less data here. In addition to worrying about things being out of date, we might also need to worry about sourcing data. E.g. for the US locations, I would advocate for keeping the following columns from the covidhubutils object: fips, location_name, geo_type, abbreviation
 - I note that `covidHubUtils::hub_locations_ecdc` has some European locations. But I wonder if @sbfnk might have suggestions of a more authoritative source for these, ideally with FIPS codes too?
 - I think keeping it simple for starters is better, so I would not suggesting adding any more info at this time.

**Comment by elray1** [comment]
One more is that I think geo_type and geo_value were there for compatibility with cmu/delphi tools. I couldn't find a full description, but there is some info about e geo_types and geo_values they support here: https://cmu-delphi.github.io/delphi-epidata/api/covidcast_geography.html

It might be worth sticking with conventions they've set up?

**Comment by nickreich** [comment]
I'm ok with leaving those columns in, per Evan's suggestion.
