### ISSUE TITLE
argument alignment for create_output_type_*() functions

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#128]
Noting that [*mean and *median functions](https://infectious-disease-modeling-hubs.github.io/hubUtils/reference/create_output_type_mean.html) have argument `is_required` whereas [other output types](https://infectious-disease-modeling-hubs.github.io/hubUtils/reference/create_output_type_quantile.html) have simply `required` as an argument. Is this desired? Or can/should we standardize these to be the same?

**Comment by nickreich** [comment]
Aha - maybe the documentation should be changed to 
```
Atomic vector of required output_type**_id** values. Can be NULL if all values are optional.
```
with changes between asterisks?

**Comment by annakrystalli** [comment]
Yes definitely! That should indeed read `output_type_id` values, not `output_type` which is confusing.
