### ISSUE TITLE
minimum and maximums for output_types

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#129]
The `value_minimum` and `value_maximum` arguments passed to `create_output_type_*()` functions are, as the documentation says "exclusive minimum/maximum" values. I interpret that to mean that the value given in that argument is a non-inclusive minimum, e.g. if `value_minimum=0` for a sample output_type then a sample with value 0 would be invalid. My take is that in most cases we will want these minimums and maximums to be inclusive rather than exclusive. E.g. I want sample x to be between 0 and 1 inclusive, where values of both 0 and 1 are allowed.

**Comment by annakrystalli** [comment]
Thanks for reporting this! I agree and had implemented checking for inclusive minima and maxima in both `hubUtils` and `hubValidations` as this is what JSON validation against schema does also, but had forgot to update this section of the docs! 🤦‍♀️

So easy fix! Will update documentation accordingly!
