### ISSUE TITLE
Replace ~ with \(x) in purrr calls that trigger object_usage_linter errors

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#141]
Relevant discussion and solution here: https://github.com/Infectious-Disease-Modeling-Hubs/.github/discussions/3#discussioncomment-8485240

Amend #139 before merging

**Comment by sbfnk** [comment]
Noting that this will introduce a dependency on `R >= 4.1.0`. If we‘re not happy with this could also consider using `function (x)` notation instead.
