### ISSUE TITLE
[WIP] Package split questions

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#142]
- [x] Currently left `load_model_metadata` in `hubUtils`.  It's not used in any of the main `hubData` or `hubAdmin` functions. It's only called by other packages in `hubValidations` so far.  Is this the right place for it?

**Comment by elray1** [comment]
Let's move `load_model_metadata` to `hubData` -- it'll mainly be used by people analyzing model outputs (e.g. when building an ensemble or a viz, it might be relevant to subset models based on metadata).

**Comment by annakrystalli** [comment]
Hehe thanks for the fast response @elray1 ! 

I'm gonna go ahead and record a bunch of questions in this issue as I work through the split and share the collated list when I've got the first drafts going. Is that ok?
