### ISSUE TITLE
[Input validation - LOAD] Scenario #1 Invalid task_id

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#16]
In this scenario, the user requests data for a task_id that does not exist. There are two scenarios where this could happen

## Incorrectly input task_id

Part of these checks is to ensure task_id are requested correctly. A user might request specific values of a task_id but there might be a typo. e.g. requesting a `loction` instead of `location`

### Options for action

- [ ] Throw an error and direct user to the invalid task id
- [ ] Throw a warning. ignore invalid task id and return data matching all other valid filters (could make the returned data significantly larger?)

### task_id not available in one or more rounds but available in others

Let's assume that task id `age_group` was not included in `round-1` of a hub but was from `round-2` and thereafter. A user requests data from `round-1` and `round-2` and includes an age group filter, let's say `6-18`. What do we want the behaviour of input validation checks to be?

### Options for action

- [ ] Throw an error (I think no but including for completeness)
- [ ] Throw a warning about `age_group` not being a valid task_id and return ALL data from `round-1` (as cannot be filtered by age group)
- [ ] Throw a warning about `age_group` not being a valid task_id and return NO data from `round-1` (as cannot be filtered by age group)
- [ ] Throw a warning and control whether ALL or NO data for rounds where the task_id is invalid through an argument.

## Distinguishing between the two situations

We may want different behaviour between the two aforementioned situations. For example if we want an error in the first situation and a warning in the second, we need to be able to distinguish between the two. One option could be that if a given task_id is not found as a valid task_id in any rounds, assume we are dealing with the first situation otherwise assume we are dealing with situation 2.

## Additional considerations

Related to my question here https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/14#issuecomment-1280621734, I'm assuming task_ids might only change in hubs with round specific task ids. Is this however strictly the case? What happens to a `round_id_from_variable `  hub? Could they ever for example add task_ids at some point and how would that be handled in the hubmeta file? Would they just add the additional task_id to their metadata or shift to a round varying metadata format with different task ids for the pre and post task id periods?

**Comment by elray1** [comment]
I vote for:

 - For your first "Options for action" point, we throw an error (first option)
 - For your second "Options for action" point, we do one of the third or fourth options. I think I prefer the third option (warn and return no data), but could potentially be convinced to provide an argument to specify behavior.

And I agree that that it makes sense to say that we are in the first situation if the input `task_id` is not valid for any rounds (i.e., there is no `round` > `model_tasks` > `.` > `task_ids` element containing the specified `task_id` as a property).
