### ISSUE TITLE
[Input validation - Submit] Scenario #1 Invalid task_id

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#19]
A team wants to submit data but one of the columns in the dataset does not correspond to a valid task id for the given round.

### Options for action

- [ ] Trow error identifying column that does not correspond to a valid task_id

**Comment by elray1** [comment]
Agree with your option for action. Note that this functionality for validating team submissions to a Hub will likely not live in the `hubUtils` package.
