### ISSUE TITLE
[Input validation - Submit] Scenario #2 Invalid task_id value

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#20]
A team wants to submit data but one of the valid task_id columns in the dataset contains a value that is not valid for that task id for a given round.

### Options for action

- [ ] Throw error identifying the invalid task_id value (and perhaps the location of affected cells in the file)?

**Comment by elray1** [comment]
Agree with your option for action. Note that this functionality for validating team submissions to a Hub will likely not live in the `hubUtils` package. In a separate context, we should think through this more carefully, e.g., distinguishing between `required` and `optional` values for `task_id` variables and specifying a more complete set of scenarios around whether or not those values occur in the submission file as well.
