### ISSUE TITLE
[Input validation - Submit] Scenario #3 Missing required task_id value

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#21]
A team wants to submit data but one of the valid task_id columns in the dataset does not contains a required value for that task id for a given round.

### Options for action

- [ ] Throw error identifying the missing required task_id value?

**Comment by elray1** [comment]
Agree with your option for action. Note that this functionality for validating team submissions to a Hub will likely not live in the `hubUtils` package.
