### ISSUE TITLE
`round-id` label in `round_id_from_variable` hubs

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#22]
Currently in the `hub_connection` class object I'm attaching 3 relevant metadata summary attributes:
- `round_ids`: 
  - in round varying hubs -> a vector of round id names
  - in `round_id_from_variable`  hubs -> the `round_id_variable`, e.g. `"origin_date"`
- `task_id_names`:
  - in round varying hubs -> a named list of task id names per round
  - in `round_id_from_variable`  hubs -> a character vector of task id names, indicating their consistency across rounds
- `task_ids_by_round` a logical value, `TRUE` if round varying hub, `FALSE` if  `round_id_from_variable`  hub making it easier to distinguish the two types of hubs.

See examples:

``` r
library(hubUtils)
# round_id_from_variable hub
connect_hub(system.file("hub_1", package = "hubUtils")) |>
    attributes()
#> $names
#> [1] "round_id_from_variable"
#> 
#> $hubmeta_path
#> /Users/Anna/Library/R/arm64/4.2/library/hubUtils/hub_1/hubmeta.json
#> 
#> $hub_path
#> [1] "/Users/Anna/Library/R/arm64/4.2/library/hubUtils/hub_1"
#> 
#> $task_id_names
#> [1] "origin_date" "location"    "horizon"    
#> 
#> $round_ids
#> [1] "origin_date"
#> 
#> $task_ids_by_round
#> [1] FALSE
#> 
#> $class
#> [1] "list"           "hub_connection"
# round varying hub
connect_hub(system.file("scnr_hub_1", package = "hubUtils")) |>
    attributes()
#> $names
#> [1] "round-1" "round-2"
#> 
#> $hubmeta_path
#> /Users/Anna/Library/R/arm64/4.2/library/hubUtils/scnr_hub_1/hubmeta.json
#> 
#> $hub_path
#> [1] "/Users/Anna/Library/R/arm64/4.2/library/hubUtils/scnr_hub_1"
#> 
#> $task_id_names
#> $task_id_names$`round-1`
#> [1] "origin_date" "scenario_id" "location"    "target"      "horizon"    
#> 
#> $task_id_names$`round-2`
#> [1] "origin_date" "scenario_id" "location"    "target"      "age_group"  
#> [6] "horizon"    
#> 
#> 
#> $round_ids
#> [1] "round-1" "round-2"
#> 
#> $task_ids_by_round
#> [1] TRUE
#> 
#> $class
#> [1] "list"           "hub_connection"
```

<sup>Created on 2022-10-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This however leads to inconsistencies in the form of how task id metadata are held. There was a question about simplifying to a single vector where task ids are consistent across rounds in round varying hubs (https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/14#issuecomment-1269564495) and Evan seemed to like the idea. However when it comes to implementation, and given such simplification cannot always be guaranteed, the inconsistency of output is ending up requiring checks and extra conditional logic according to object type (list or vector) returned in order to make use of the info downstream. 

On the other hand, having a named list of task ids in all cases actually simplifies the back-end significantly as we can just use the required round id in round varying hubs and a consistent round id name in non varying hubs so I'm leaning towards that.

If you agree with this approach, this leads to a question of what to assign as the consistent `round-id` name of the single task_id_names element in the case of a `round_id_from_variable ` metadata structure. Here are some options:

- Leave as `round_id_from_variable`.  This is simple but not that informative
- Change to the value of the actual variable acting as round_id identifier (e.g. `origin_date`). This is much more meaningful I feel. In this case I also suggest that, when reading in hubmeta, we also replace `round_id_from_variable` (which is the name of the single top level element) with the variable name acting as round_id identifier. This would make validating `round_id` argument inputs against the `round_ids` attribute of `hub_connection` the same as in the case of round varying hubs. It would also mean we would have a meaningful value to assign in the case of round_id = NULL inputs (in round aware functions discussed in #14) against  into the nested metadata structure and consistent between hubs with round varying task ids and  `round_id_from_variable` hubs. 

I'm personally leaning towards the second option but thoughts welcome. Also, while internal validation etc functions can make use of the consistent structure, we could have user facing functions where metadata are simplified if possible.

**Comment by elray1** [comment]
The second option sounds fine to me. Note that even in hubs where the round id is coming from a variable, to be safe I think that we may need to collect the possible values of that variable by combining across multiple entries in a `model_tasks` array. This is related to discussion [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/issues/14#issuecomment-1284441089).
