### ISSUE TITLE
Use magrittr `%>%` or base R `|>` pipe?

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#23]
Was wondering if you had a preference for importing `magrittr` pipe or base R `|>` pipe. 

I've been using base R `|>` pipe so far but that immediately sets  R 4.1.0 or greater as a dependency so on second thought, asking folks to upgrade R to use the package might be a big ask.

**Comment by elray1** [comment]
I support using to `%>%` (as we discussed an you have already done; just commenting to have written record of this discussion :) )
