### ISSUE TITLE
Evaluate the need for accommodating multiple model output file formats in a single hub

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#40]
In a previous meeting there was mention by a number of you of mixing model output files of different format (e.g. CSV and parquet) in the same hub. I'm trying to figure out whether this is something we might need to support and if so what the best approach would be so could you let me know:

1. If this is something you have implemented or think you might need to implement at some point in one of your hubs.

2. Whether you have different file formats intermixed within individual directories or whether you separate them out into separate directories for each format.

**Comment by LucieContamin** [comment]
For the US Scenario Modeling Hub, we often have different file format for the same rounds. 

- To read the files, we have an internal function that was written to be able to read all the possible files individually and output a data.frame.  I am looking at complementing that function for speed and "arrow processing".

- They are stored in the same directories (organized by team model output):
`data-processed/team-model/YYYY-MM-DD-team-model.csv or .zip, .gz, .parquet, etc.`

**Comment by annakrystalli** [comment]
Problem being investigated here: https://github.com/apache/arrow/issues/34640
