### ISSUE TITLE
Create dummy data of epiweek cdf forecasts

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#51]
To expand testing, I need to generate some slightly more elaborate test hub cases and want to include examples of an epiweek cdf output type. 

Firstly, does this seem like reasonable model output data?

|output_type|type_id |value      |
|-----------|--------|-----------|
|cdf        |EW202301|0.007295056|
|cdf        |EW202302|0.029636164|
|cdf        |EW202303|0.081765416|
|cdf        |EW202304|0.172991608|
|cdf        |EW202305|0.300708276|
|cdf        |EW202306|0.449711056|
|cdf        |EW202307|0.598713836|
|cdf        |EW202308|0.729091268|
|cdf        |EW202309|0.830495937|
|cdf        |EW202310|0.901479206|
|cdf        |EW202311|0.946650377|
|cdf        |EW202312|0.973000227|
|cdf        |EW202313|0.987188607|
|cdf        |EW202314|0.994282798|
|cdf        |EW202315|0.997593420|
|cdf        |EW202316|0.999041817|
|cdf        |EW202317|0.999638216|
|cdf        |EW202318|0.999870149|
|cdf        |EW202319|0.999955598|
|cdf        |EW202320|0.999985505|

``` r
epi_tab <- tibble::tibble(
    output_type = "cdf",
    type_id = glue::glue("EW2023{sprintf('%02d', 1:20)}"),
    value = ppois(1:20, lambda = 7)
)

library(ggplot2)
ggplot(epi_tab,
       aes(x = type_id, y = value, group = output_type)) +
    geom_line() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

![](https://i.imgur.com/jB3x9rh.png)

<sup>Created on 2023-04-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I have a few follow up questions to ensure I understand what's being modelled here correctly:

- Am I right in assuming that the target associated with such an output type is "peak week" of some outcome?
- How does a cdf of peak week relate to other target_ids like `"origin_date"` or `"horizon"`?
  - Does `"origin_date"`  limit the start of the time frame over which the cdf of peak week is calculated?
  - And what is the meaning of horizon when peak week is being forecasted? Would that just be `NA`?

Any pointers on how to ensure I get this dummy data right welcome, as well as links to hubs already collecting such data (I did a quick scavenge of a few hubs I know of but couldn't locate any)

**Comment by nickreich** [comment]
Here is [a file](https://github.com/FluSightNetwork/cdc-flusight-ensemble/blob/master/model-forecasts/real-time-ensemble-models/equal-weights/EW01-2020-equal-weights.csv) that has a "season peak week" target, although only defined for "bin" output_type (similar to our `pmf`).

> Am I right in assuming that the target associated with such an output type is "peak week" of some outcome?
Yes, this is one plausible target with this representation.

> Does "origin_date" limit the start of the time frame over which the cdf of peak week is calculated?
Typically no, the distribution of peak week target would be the same for origin_date. If the model is convinced the peak has passed, have cdf values that are a bunch of 0s then 1s.

> And what is the meaning of horizon when peak week is being forecasted? Would that just be NA?
Yes. horizon only has a meaning for what we call in Zoltar a "step-ahead" target, which is looking 1, 2, etc.. time units ahead.

**Comment by annakrystalli** [comment]
Useful example: https://github.com/cdcepi/Flusight-forecast-data/commit/1121029518a2a2127ce06f30b9ffa538b66dbaa2
