### ISSUE TITLE
add standardize_column_names() function

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#63]
This would be designed to live in the workflow after "collect()" and before something like a plot or ensembling of forecasts. E.g. Currently when data are read in, a `model` column is inferred based on the folder name where the data originates. We would like to have the recommended setup be that `model_abbr` and `team_abbr` columns are inferred from a nested folder structure. however to support legacy code, we'd also like to have a function that could split a non-nested folder structure based on a "[team_name]-[model_name]" kind of folder name.

**Comment by annakrystalli** [comment]
Just double checking but I feel this issue is obsolete now as we decide against it? Or do we want to include a utility function that can perform this splitting?

**Comment by nickreich** [comment]
I wonder if it's still relevant but for different reasons. e.g. for a legacy hub might we want to run it through a function like this to end up with "model_id" and "output_type", "output_type_id", "value"  columns, etc...?
