### ISSUE TITLE
Create `as_model_out_df()` function and `model_out_df` S3 class

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#66]
- `as_model_out_df()` function
- `validate_model_out_df()` function

For more details, refer to dicussion in #33

**Comment by LucieContamin** [comment]
Should the "as_..." function have an optional feature to drop empty columns?

**Comment by annakrystalli** [comment]
@LucieContamin implemented using argument `remove_empty` (which defaults to `FALSE`)

**Comment by LucieContamin** [comment]
Perfect, thank you!
