### ISSUE TITLE
Update in `hubUtils:::open_hub_dataset()`

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubUtils#73]
To read csv files, it seems to be necessary to have the `model_id` information in the input "schema" (output of `create_hub_schema()`

**Comment by annakrystalli** [comment]
Using arrow version 12.0.0

**Comment by LucieContamin** [comment]
Example repo: https://github.com/Infectious-Disease-Modeling-Hubs/example-complex-scenario-hub

**Comment by annakrystalli** [comment]
Hey @LucieContamin 

I _think_ this is fixed (it works on my machine! 🤷‍♀️😂) but let's make sure it works on your machine too 😜

Can you try:
```r
remotes::install_github("Infectious-Disease-Modeling-Hubs/hubUtils",
                       dependencies = TRUE, ref = "val-hub-config")
```
Restart R

```r
con <- connect_hub("path/to/your/hub")
con
con %>% filter(origin_date == "2021-03-07", output_type_id == 0.025) %>% collect()
```

to see if everything works?

**Comment by annakrystalli** [comment]
Works now.
