### ISSUE TITLE
Unexpected successful validation of malformed tasks.json file

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubUtils#76]
The tasks.json file in the example-simple-forecast-hub currently has a `target_metadata` block that is in the wrong location, [here](https://github.com/Infectious-Disease-Modeling-Hubs/example-simple-forecast-hub/blob/85b86710d887315ce77ff580ac3ae46fe2d1f128/hub-config/tasks.json#L125). That block is nested within the `"output_type"` block, but I think it should not be there. Note that the `output_type` [specification](https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/e41978fa73be9ab47405c41613da95868d8f42cf/v1.0.0/tasks-schema.json#L398) in the schema file does not include `target_metadata` as a valid output type.

However, running `hubUtils::validate_config` yields a passing result:
```r
> library(hubUtils)
> hubUtils::validate_config(".")
Loading required namespace: jsonvalidate
✔ Successfully validated config file ./hub-config/tasks.json against schema <https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/v1.0.0/tasks-schema.json>
[1] TRUE
attr(,"config_path")
./hub-config/tasks.json
attr(,"schema_version")
[1] "v1.0.0"
attr(,"schema_url")
https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/v1.0.0/tasks-schema.json
```

**Comment by annakrystalli** [comment]
😳 Very strange! That should indeed be failing. Will invertigate!

**Comment by annakrystalli** [comment]
Turns out additional properties are just ignored by default and `additionalProperties; false` is required to explicitly throw an error https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

Fixed in the schema via https://github.com/Infectious-Disease-Modeling-Hubs/schemas/pull/51
