### ISSUE TITLE
Compile example `hubmeta.json` files and associated mini-hubs

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#8]
To validate that metadata in `hubmeta.json` files can be used effectively to support loading data from a variety of hubs I will need:
-  representative `hubmeta.json` files
- Associated example mini hubs to validate functions for loading data against. These will be useful for testing and demos in vignettes. Options:
    - Internal: If small enough they would Ideally live in `inst` and be accessible through `system.file()` calls. 
    - External: if the total size of files to capture enough hub diversity of characteristics then we could host demo data as separate demo hubs. This would make testing slower then and require an internet connection to run tests.

**Comment by annakrystalli** [comment]
## Resources
- https://github.com/reichlab/hub-infrastructure-experiments/tree/main/metadata-format-examples/simple-example

**Comment by elray1** [comment]
I think we should be able to assemble small enough examples that this could live within this folder

**Comment by nickreich** [comment]
Here is a link to an example hub: https://github.com/cdcepi/Flusight-forecast-data
