### ISSUE TITLE
create function for creating and example or template submission file or data.frame from tasks.json

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#82]
It would be nice to create a dummy/example file of what a valid submission might look like. Maybe there could be an option to create a minimal example (e.g. with only required or one optional value for each task_id) or to create a "complete" example (all combinations of task_id values).

**Comment by annakrystalli** [comment]
Definitely! This will be an integral part of test/example data for `hubValidations`
