### ISSUE TITLE
If multiple rounds exist in `round_id_from_variable: true` hubs, check that rounds do not share round_id variable values

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#85]
See example [`tasks.json`](https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/blob/main/inst/testhubs/simple/hub-config/tasks.json) in simple hub example reflecting a situation where a new round is created later on to enable collecting an `age_group` task ID.

I've been assuming that this would be the correct way to handle such changes to hub task IDs over time in hubs where `round_id_from_variable: true`. Is this a correct assumption? (and therefore valid issue?)

Confirmation welcome @nickreich @elray1 @rborchering

**Comment by nickreich** [comment]
Yes. this seems like a valid issue and a correct assumption to me.

**Comment by annakrystalli** [comment]
Just trying to wrap this issue up and have an additional questions:
- Is there any situation where a hub might include multiple rounds, some of which are configured as `round_id_from_variable: true` and some `round_id_from_variable: false`?
- In rounds where `round_id_from_variable: true`, would it ever be acceptable for the task ID specified in `round_id` to change in subsequent rounds or should it always be the same within a hub?
-  If the answers to the above questions are that none (`round_id_from_variable` /  task ID specified in `round_id`) should vary across rounds, should I add this checks to the config validation. 

I have noted in an newly opened issue that we are lacking any example hubs with `round_id_from_variable: false` configuration which makes testing validation of such hubs tricky. https://github.com/Infectious-Disease-Modeling-Hubs/hubValidations/issues/8  

Would be really useful to have an understanding of what such an example hub might look like.
 Even just starting with an example `tasks.json` would be a great help.
