### ISSUE TITLE
 `connect_hub()` returns an error when hub does not contain all accepted file format (admin.json information)

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubUtils#95]
If we use `connect_hub()` without setting the `file_format` parameters and by providing the information in the hub associated `admin.json` files and if the `file_format` in the `admin.json` contains more file format than present in the hub, `connect_hub` seems to fail reading all the files and returns a non informative error.

For example: if we have a hub with
- for `admin.json`:
```
"file_format":["parquet", "csv"],
"model_output_dir": "data-processed"
```
- in the associated `data-processed/`:
    - `team1_modela/`
         - `file1.parquet`
    - `team2_modelb/`
         - `file1.parquet`
         
- if we run  `connect_hub()`  we got an arrow error :
```
ds <- hubUtils::connect_hub(".")
Error in `purrr::map()`:
ℹ In index: 2.
Caused by error in `arrow::open_dataset()`:
! Invalid: No non-null segments were available for field 'model_id'; couldn't infer type
Run `rlang::last_trace()` to see where the error occurred.
```

As I understand, the error is link to the internal function `open_hub_dataset()` that expect some "csv" files and called the function 
`arrow::open_dataset()` to read 0 csv files.

I am not sure what the expected behavior should be:
Maybe the function should contain a test, for each file format, if files in this format are present:
    - if present: called `open_hub_dataset()`
    - if not present: should it returns a Message, Warning or an Error or nothing?
I think a message or something in the output object might be informative and more expected as we describe the `file_format` field in `admin.json` as "Accepted file formats of model output files."

**Comment by annakrystalli** [comment]
Thanks for the bug report! I've been monitoring this using missing `arrow` files but `csv`s behave differently so I missed this bug!

I've added a solution in a9a7bd5799fcf04a52a0de828df96cd52e3e3d06 that also fixes related issue I came across while developing in (#97)
